name: Build Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

defaults:
  run:
    shell: bash

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3

  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf
    steps:
    - name: Checkout commit
      uses: actions/checkout@v2
    - name: Build app
      run: |
        . $IDF_PATH/export.sh
        idf.py build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: compiled-binary
        retention-days: 7
        path: |
          build/bootloader/bootloader.bin
          build/partition_table/partition-table.bin
          build/makerTerminal.bin
